### Registro de usuario
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "email": "test5@correo.com",
  "password": "miPassword123"
}

### Validar código
POST http://localhost:3001/api/auth/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTMwNDc2N2YwMTkwMDZiOGI2NjU0OCIsImlhdCI6MTc0MjkzMTA2MiwiZXhwIjoxNzQyOTM4MjYyfQ.0Wrv78Tq7JbB3FKTj3sgiPEP6sMLNJ4CjylQuJwsjf8
Content-Type: application/json

{
  "code": "895248"
}


### Login
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "test4@correo.com",
  "password": "miPassword123"
}

### Actualizar perfil del usuario (Onboarding)
PATCH http://localhost:3001/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTMwMzAzZDRiNDcwN2QzNmM4ZTUwOCIsImlhdCI6MTc0MzM1MDM2NCwiZXhwIjoxNzQzMzU3NTY0fQ.hhpDG2PxWTlteVfz7Xz8H3kiM1aPneijVhA42jNNMJs
Content-Type: application/json

{
  "fullName": "Juan Pérez",
  "phone": "+34 123 456 789",
  "company": {
    "name": "Mi Empresa",
    "sector": "Software",
    "country": "España",
    "size": "10-50"
  }
}

### Obtener perfil del usuario autenticado
GET http://localhost:3001/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTMwMzAzZDRiNDcwN2QzNmM4ZTUwOCIsImlhdCI6MTc0MzM1MDM2NCwiZXhwIjoxNzQzMzU3NTY0fQ.hhpDG2PxWTlteVfz7Xz8H3kiM1aPneijVhA42jNNMJs

### Eliminar usuario (soft delete)
DELETE http://localhost:3001/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTMwMzAzZDRiNDcwN2QzNmM4ZTUwOCIsImlhdCI6MTc0MzM1MDM2NCwiZXhwIjoxNzQzMzU3NTY0fQ.hhpDG2PxWTlteVfz7Xz8H3kiM1aPneijVhA42jNNMJs


### Recuperar contraseña
POST http://localhost:3001/api/auth/recover-password
Content-Type: application/json

{
  "email": "test4@correo.com"
}
