### Registro de usuario
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "email": "test7@correo.com",
  "password": "miPassword123"
}

### Validar código
POST http://localhost:3001/api/auth/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDhkNWQ3MDNmMTcwNWVmMzQxNDQwZSIsImlhdCI6MTc0NTQwOTQ5NSwiZXhwIjoxNzQ1NDE2Njk1fQ.1BIZbhT1JnCDgVKh6aOHv_9UNqvv4d1e9sxBcrzNGkQ
Content-Type: application/json

{
  "code": "895248"
}


### Login
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "test7@correo.com",
  "password": "miPassword123"
}

### Actualizar perfil del usuario (Onboarding)
PATCH http://localhost:3001/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDhkNWQ3MDNmMTcwNWVmMzQxNDQwZSIsImlhdCI6MTc0NTQwOTUzMywiZXhwIjoxNzQ1NDE2NzMzfQ.-aUkZEjIAk8o_il3QBMIe7ZidnfXaOWDHJBOi4HylnA
Content-Type: application/json

{
  "fullName": "Juan Pérez",
  "phone": "+34 123 456 789",
  "company": {
    "name": "Mi Empresa",
    "sector": "Software",
    "country": "España",
    "size": "10-50"
  }
}

### Obtener perfil del usuario autenticado
GET http://localhost:3001/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDhkNWQ3MDNmMTcwNWVmMzQxNDQwZSIsImlhdCI6MTc0NTQwOTUzMywiZXhwIjoxNzQ1NDE2NzMzfQ.-aUkZEjIAk8o_il3QBMIe7ZidnfXaOWDHJBOi4HylnA

### Eliminar usuario (soft delete)
DELETE http://localhost:3001/api/auth/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDhkNWQ3MDNmMTcwNWVmMzQxNDQwZSIsImlhdCI6MTc0NTQwOTUzMywiZXhwIjoxNzQ1NDE2NzMzfQ.-aUkZEjIAk8o_il3QBMIe7ZidnfXaOWDHJBOi4HylnA


### Recuperar contraseña
POST http://localhost:3001/api/auth/recover-password
Content-Type: application/json

{
  "email": "test7@correo.com"
}

### Invitar usuario guest
POST http://localhost:3001/api/auth/invite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDhkNWQ3MDNmMTcwNWVmMzQxNDQwZSIsImlhdCI6MTc0NTQwOTUzMywiZXhwIjoxNzQ1NDE2NzMzfQ.-aUkZEjIAk8o_il3QBMIe7ZidnfXaOWDHJBOi4HylnA
Content-Type: application/json

{
  "email": "javiernoez2905@gmail.com"
}
